# Generated by Django 5.2.10 on 2026-01-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.JSONField(blank=True, null=True)),
                ('sequence_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
