# Generated by Django 5.2.10 on 2026-01-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midlpred', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proteinsequence',
            options={'ordering': ['-created_at'], 'verbose_name': 'Séquence protéique', 'verbose_name_plural': 'Séquences protéiques'},
        ),
        migrations.AlterField(
            model_name='proteinsequence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='proteinsequence',
            name='prediction',
            field=models.JSONField(blank=True, null=True, verbose_name='Résultat de prédiction'),
        ),
        migrations.AlterField(
            model_name='proteinsequence',
            name='sequence',
            field=models.TextField(verbose_name='Séquence protéique'),
        ),
        migrations.AlterField(
            model_name='proteinsequence',
            name='sequence_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID de séquence'),
        ),
    ]
