# Generated by Django 5.1.3 on 2026-03-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midlpred', '0002_alter_proteinsequence_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proteinsequence',
            options={'ordering': ['-created_at'], 'verbose_name': 'Protein sequence', 'verbose_name_plural': 'Proteins sequences'},
        ),
        migrations.AlterField(
            model_name='proteinsequence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='proteinsequence',
            name='prediction',
            field=models.JSONField(blank=True, null=True, verbose_name='Prediction result'),
        ),
        migrations.AlterField(
            model_name='proteinsequence',
            name='sequence',
            field=models.TextField(verbose_name='Protein sequence'),
        ),
        migrations.AlterField(
            model_name='proteinsequence',
            name='sequence_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sequence ID'),
        ),
    ]
